CAcbFile::GetCueNameFromCueId
hozuki/libcgss pull request #5
Opened 2018-10-21 13:28 UTC by esterTion

2018-10-21 16:30 UTC, hozuki requested changes

2018-10-21 16:30 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
> +static char useCueName = 0;
Don't use global variables. Use parameters and arguments. Also there is `bool_t`.

2018-10-21 16:30 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
> +    cout << "acb2wavs <acb file> [-a <key1> -b <key2> -n]" << endl;
A switch/arg inside brackets means optional and **independent**. E.g.:

```plain
FINDSTR [/B] [/E] [/L] [/R] [/S] [/I] [/X] [/V] [/N] [/M] [/O] [/P] [/F:file]
        [/C:string] [/G:file] [/D:dir list] [/A:color attributes] [/OFF[LINE]]
        strings [[drive:][path]filename[ ...]]
```

2018-10-21 16:30 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
> +                    useCueName = 1;
`TRUE` is defined.

2018-10-21 16:30 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
> +            fprintf(stdout, "%s ", extractFileName.c_str());
What is the purpose of this `fprintf` call here?

2018-10-21 16:30 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
> +        if (useCueName) {
Formatting: new line

2018-10-21 16:30 UTC, hozuki commented on src/lib/ichinose/CAcbFile.cpp
> +    return CAcbFile::GetSymbolicFileNameFromCueId(cueId);
Formatting: new line

2018-10-21 16:30 UTC, hozuki commented on src/lib/ichinose/CAcbFile.cpp
> +        if (cue.waveformId == cueId) return string(cue.cueName);
Formatting: new line and braces

2018-10-21 16:30 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
>          auto extractFileName = CAcbFile::GetSymbolicFileNameFromCueId(record.cueId);
Code structure. Multiple assignings are not necessary.

```cpp
string s;

if (...) {
    s = ...
} else {
    s = ...
}
```

`std::string` will handle the by-value returns of `GetSymbolicFileNameFromCueId` and `GetCueNameFromCueId`.
Also in this case, do not call `ReplaceExtension` twice (though it does not panic). Beware of semantics.

2018-10-22 00:42 UTC, esterTion commented on src/apps/acb2wavs/acb2wavs.cpp
> +static char useCueName = 0;
So where to store other than global?

2018-10-22 00:45 UTC, esterTion commented on src/apps/acb2wavs/acb2wavs.cpp
>          auto extractFileName = CAcbFile::GetSymbolicFileNameFromCueId(record.cueId);
1. made this structure to avoid change `auto`
2. names from `GetCueNameFromCueId` could be `xxxx.hca`, or `dat_%06u.bin`

2018-10-23 18:13 UTC, hozuki requested changes

2018-10-23 18:13 UTC, hozuki commented on src/lib/ichinose/CAcbFile.cpp
> +    sprintf(buffer, "dat_%06u.hca", cueId);
The audio type is not always HCA (as you have pointed out, could be ADX or else)

2018-10-23 18:13 UTC, hozuki commented on src/apps/acb2wavs/acb2wavs.cpp
> +static bool useCueName = false;
Use parameter/argument instead of global variable here. Generally, use global variables as little as possible.

2019-01-08 13:20 UTC, merged